export const Groups = [
    {
      id: 1,
      title: "Discover the Ancient Temples of Bagan",
      days: 3,
      place: "Bagan, Myanmar",
      about: "Explore thousands of ancient temples, hot air balloon rides at sunrise, and local Burmese cuisine.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-06-10",
      endDate: "2025-06-13",
      activities: ["Temple tours", "Balloon ride", "River cruise"],
      availableSpots: 2,
      expectedCost: 320,
      startingPointOfGroup: "Yangon",
      owner: "user_01",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/bagan.jpg"
    },
    {
      id: 2,
      title: "Sahara Desert Adventure",
      days: 4,
      place: "Merzouga, Morocco",
      about: "Camel trekking, sandboarding, and camping under the stars in the Sahara Desert.",
      tags: ["Adventure", "Nature", "Wildlife"],
      startDate: "2025-07-01",
      endDate: "2025-07-05",
      activities: ["Camel trekking", "Desert camping", "Star gazing"],
      availableSpots: 4,
      expectedCost: 470,
      startingPointOfGroup: "Marrakech",
      owner: "user_02",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/sahara.jpg"
    },
    {
      id: 3,
      title: "Tokyo Tech and Tradition Tour",
      days: 5,
      place: "Tokyo, Japan",
      about: "Blend of ultra-modern tech, historic temples, anime culture, and street food exploration.",
      tags: ["Historic", "Cultural", "City Tour"],      
      startDate: "2025-05-20",
      endDate: "2025-05-25",
      activities: ["Temple visit", "Akihabara tour", "Sushi making"],
      availableSpots: 1,
      expectedCost: 1250,
      startingPointOfGroup: "Narita Airport",
      owner: "user_03",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/tokyo.jpg"
    },
    {
      id: 4,
      title: "Highlands and Lochs",
      days: 4,
      place: "Scottish Highlands, UK",
      about: "Visit castles, hike in the moors, and discover the legends of Loch Ness.",
      tags: ["Nature", "Adventure", "Winter"],      
      startDate: "2025-08-12",
      endDate: "2025-08-16",
      activities: ["Hiking", "Castle tour", "Whisky tasting"],
      availableSpots: 3,
      expectedCost: 620,
      startingPointOfGroup: "Edinburgh",
      owner: "user_04",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/highlands.jpg"
    },
    {
      id: 5,
      title: "Andean Escape",
      days: 6,
      place: "Cusco & Machu Picchu, Peru",
      about: "Journey through the Sacred Valley and hike to the iconic Machu Picchu ruins.",
      tags: ["City", "Beach", "Cultural"],
      startDate: "2025-09-10",
      endDate: "2025-09-16",
      activities: ["Inca Trail", "Cultural sites", "Photography"],
      availableSpots: 2,
      expectedCost: 850,
      startingPointOfGroup: "Lima",
      owner: "user_05",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/machu-picchu.jpg"
    },
    {
      id: 6,
      title: "Bali Island Retreat",
      days: 7,
      place: "Bali, Indonesia",
      about: "Experience spiritual tranquility, surf beaches, and rice terraces in Ubud.",
      tags: ["City", "Beach", "Cultural"],
      startDate: "2025-07-05",
      endDate: "2025-07-12",
      activities: ["Temple visit", "Surfing", "Spa retreat"],
      availableSpots: 2,
      expectedCost: 950,
      startingPointOfGroup: "Denpasar",
      owner: "user_06",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/bali.jpg"
    },
    {
      id: 7,
      title: "Patagonia Hiking Tour",
      days: 5,
      place: "El Chaltén, Argentina",
      about: "Trek through glacier-filled national parks and rugged mountain landscapes.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-11-01",
      endDate: "2025-11-06",
      activities: ["Hiking", "Glacier walk", "Wildlife spotting"],
      availableSpots: 5,
      expectedCost: 1150,
      startingPointOfGroup: "Buenos Aires",
      owner: "user_07",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/patagonia.jpg"
    },
    {
      id: 8,
      title: "Desert Mirage Tour",
      days: 3,
      place: "Wadi Rum, Jordan",
      about: "Explore red sandstone valleys, stargaze in the desert, and visit Petra.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-10-15",
      endDate: "2025-10-18",
      activities: ["4x4 tour", "Bedouin camp", "Petra visit"],
      availableSpots: 4,
      expectedCost: 420,
      startingPointOfGroup: "Amman",
      owner: "user_08",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/wadi-rum.jpg"
    },
    {
      id: 9,
      title: "Canadian Rockies Expedition",
      days: 5,
      place: "Banff & Jasper, Canada",
      about: "Turquoise lakes, alpine peaks, and glacier-fed rivers make this a nature lover's dream.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-06-20",
      endDate: "2025-06-25",
      activities: ["Lake Louise", "Hiking", "Hot springs"],
      availableSpots: 3,
      expectedCost: 1050,
      startingPointOfGroup: "Calgary",
      owner: "user_09",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/rockies.jpg"
    },
    {
      id: 10,
      title: "Historic Cities of Europe",
      days: 10,
      place: "Rome, Paris, Prague",
      about: "A whirlwind tour of Europe’s most iconic historical cities and their landmarks.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-08-01",
      endDate: "2025-08-11",
      activities: ["Museum visits", "Walking tours", "Local food"],
      availableSpots: 2,
      expectedCost: 2600,
      startingPointOfGroup: "Rome",
      owner: "user_10",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/europe.jpg"
    },
    {
      id: 11,
      title: "Amazon Rainforest Discovery",
      days: 6,
      place: "Manaus, Brazil",
      about: "Boat through the Amazon River and explore one of the world's richest ecosystems.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-09-18",
      endDate: "2025-09-24",
      activities: ["Boat tours", "Wildlife watching", "Jungle walk"],
      availableSpots: 2,
      expectedCost: 1350,
      startingPointOfGroup: "Manaus",
      owner: "user_11",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/amazon.jpg"
    },
    {
      id: 12,
      title: "Dolomites Alpine Adventure",
      days: 4,
      place: "Dolomites, Italy",
      about: "Hike through jagged mountain trails and relax in scenic alpine villages.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-07-22",
      endDate: "2025-07-26",
      activities: ["Via ferrata", "Cable car", "Local food"],
      availableSpots: 3,
      expectedCost: 720,
      startingPointOfGroup: "Venice",
      owner: "user_12",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/dolomites.jpg"
    },
    {
      id: 13,
      title: "Cultural Colors of India",
      days: 7,
      place: "Rajasthan, India",
      about: "Palaces, deserts, festivals, and spicy cuisine all in one colorful state.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-10-01",
      endDate: "2025-10-08",
      activities: ["Fort tours", "Camel ride", "Street food"],
      availableSpots: 4,
      expectedCost: 530,
      startingPointOfGroup: "Jaipur",
      owner: "user_13",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/rajasthan.jpg"
    },
    {
      id: 14,
      title: "New Zealand Road Trip",
      days: 8,
      place: "South Island, New Zealand",
      about: "Epic road trip through fjords, mountains, and lakes with outdoor adventures.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-12-01",
      endDate: "2025-12-09",
      activities: ["Road trip", "Skydiving", "Hiking"],
      availableSpots: 3,
      expectedCost: 1800,
      startingPointOfGroup: "Christchurch",
      owner: "user_14",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/new-zealand.jpg"
    },
    {
      id: 15,
      title: "Vietnam Heritage Trail",
      days: 7,
      place: "Hanoi to Hoi An",
      about: "Discover Vietnam’s rich heritage through old towns, lantern festivals, and scenic bays.",
      tags: ["Cultural", "Historic", "Scenic"],
      startDate: "2025-11-05",
      endDate: "2025-11-12",
      activities: ["Cultural tour", "Boat ride", "Street food crawl"],
      availableSpots: 4,
      expectedCost: 650,
      startingPointOfGroup: "Hanoi",
      owner: "user_15",
      createdOn: "2025-05-07T00:00:00Z",
      image: "https://example.com/images/vietnam.jpg"
    }
  ];
  